# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 006dd6f9-4e12-46d8-aa01-9fa55ebc1285-capi-aws-check
  namespace: 006dd6f9-4e12-46d8-aa01-9fa55ebc1285
spec:
  template:
    metadata:
      name: 006dd6f9-4e12-46d8-aa01-9fa55ebc1285-capi-aws
    spec:
      serviceAccountName: 006dd6f9-4e12-46d8-aa01-9fa55ebc1285-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 006dd6f9-4e12-46d8-aa01-9fa55ebc1285
        - 006dd6f9-4e12-46d8-aa01-9fa55ebc1285
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 006dd6f9-4e12-46d8-aa01-9fa55ebc1285-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
